services:
  mini-ml-platform-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=api
    container_name: mini-ml-platform-api
    volumes:
     - ./model:/app/model
