services:

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - mlnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  minio-client:
    image: minio/mc
    container_name: minio-client
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 10 &&
      mc alias set local http://minio:9000 admin admin123 &&
      mc mb -p local/model || true &&
      mc policy set public local/model || true
      "
    networks:
      - mlnet

  ml-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: ml-api
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
      BUCKET_NAME: model
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 2s
    networks:
      - mlnet

  ml-trainer:
    build:
      context: .
      dockerfile: Dockerfile.trainer
    container_name: ml-trainer
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
      BUCKET_NAME: model
    volumes:
      -  ./src/main/resources/data:/data
    networks:
      - mlnet

  test-e2e:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: test-e2e
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - mlnet
    environment:
      MODEL_ID: iris
      RESTASSURED_BASE_URI: http://ml-api      # a API chamada pelo nome de serviço
      RESTASSURED_PORT: 8080
    entrypoint:
      [
        "sh", "-c",
        "echo '⏳ Waiting for ml-api healthcheck…' && \
         until curl -sSf http://ml-api:8080/actuator/health; do sleep 2; done && \
         echo '✅ ml-api is up, running E2E tests' && \
         mvn test --no-transfer-progress -Dtest=ModelApiE2ETest"
      ]
    tty: true
    stdin_open: true

volumes:
  minio_data:

networks:
  mlnet:    
    external: false